import = ["/home/leiswatch/.config/alacritty/themes/tokyonight-night.toml"]

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 5, y = 5 }
opacity = 1
blur = false
startup_mode = "Windowed"

[scrolling]
history = 99999

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font", style = "SemiBold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Medium Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "SemiBold Italic" }
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 1 }
size = 13.5

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true
