
# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sessionist'
# set -g @plugin 'tmux-plugins/tmux-cpu'
# set -g @plugin 'tmux-plugins/tmux-battery'
# set -g @plugin 'tmux-plugins/tmux-net-speed'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-copycat'

# Battery
# set -g @batt_icon_charge_tier8 '🌕'
# set -g @batt_icon_charge_tier7 '🌖'
# set -g @batt_icon_charge_tier6 '🌖'
# set -g @batt_icon_charge_tier5 '🌗'
# set -g @batt_icon_charge_tier4 '🌗'
# set -g @batt_icon_charge_tier3 '🌘'
# set -g @batt_icon_charge_tier2 '🌘'
# set -g @batt_icon_charge_tier1 '🌑'
# set -g @batt_icon_status_charged '🔋'
# set -g @batt_icon_status_charging '⚡'
# set -g @batt_icon_status_discharging '👎'

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind C-p previous-window
bind C-n next-window

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

set -s default-terminal 'screen-256color'
# set -s default-terminal 'tmux-256color'

# Continuum
set -g @continuum-save-interval '10'

# Refresh status line every 5 seconds - Good for when music is playing / update time etc
# set -g status-interval 5
setw -g history-limit 50000000
set -g @dracula-plugins "cpu-usage ram-usage battery time"
set -g @dracula-show-powerline true
set -g @dracula-show-timezone false
set -g @dracula-day-month true
set -g @dracula-military-time true
set -g @dracula-show-left-icon 🖥
set -g @dracula-cpu-usage-colors "orange dark_gray"
set -g @dracula-ram-usage-colors "green dark_gray"
set -g @dracula-battery-colors "red dark_gray"
run '~/.tmux/plugins/tpm/tpm'
