
# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-copycat'

set-option -g prefix C-a
bind-key C-a send-prefix

bind C-p previous-window
bind C-n next-window
bind C-o switch-client -n
bind C-i switch-client -p

set -g mouse on
set -g base-index 1
set -g allow-rename off
setw -g pane-base-index 1
set -g @yank_with_mouse on

# set -g default-terminal "xtmux-256color"
# set -ag terminal-overrides ",xterm-256color:RGB"

# Undercurl
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

set -g @continuum-restore 'on'

setw -g history-limit 50000000

# Rose Pine
# thm_bg="#191724"
# thm_fg="#e0def4"
# thm_black="#1F1D2E"
# thm_cyan="#9ccfd8"
# thm_gray="#403d52"
# thm_magenta="#c4a7e7"
# thm_pink="#ebbcba"
# thm_red="#eb6f92"
# thm_green="#31748f"
# thm_yellow="#f6c177"
# thm_blue="#524f67"
# thm_orange="#ebbcba"

# Catppuccin Mocha
thm_bg="#1e1e2e"
thm_fg="#cdd6f4"
thm_black="#11111b"
thm_cyan="#89dceb"
thm_gray="#313244"
thm_magenta="#cba6f7"
thm_pink="#f5c2e7"
thm_red="#f38ba8"
thm_green="#a6e3a1"
thm_yellow="#f9e2af"
thm_blue="#89b4fa"
thm_orange="#fab387"

set -g status-position bottom
set -g status "on"
set -g status-bg "${thm_black}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

set -g message-style fg="${thm_pink}",bg="${thm_black}",align="centre"
set -g message-command-style fg="${thm_blue}",bg="${thm_bg}",align="centre"

set -g pane-border-style fg="${thm_gray}"
set -g pane-active-border-style fg="${thm_blue}"

setw -g window-status-activity-style fg="${thm_fg}",bg="${thm_bg}",none
setw -g window-status-separator ""
setw -g window-status-style fg="${thm_fg}",bg="${thm_black}",none

set -g status-left "#{?client_prefix,#[bg=$thm_red],#[bg=$thm_cyan]}#[fg=$thm_black] #{?client_prefix,#[bg=$thm_red],#[bg=$thm_cyan]}#[fg=$thm_black] #S "
set -g status-right "#[fg=$thm_black,bg=$thm_yellow]  #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=$thm_black,bg=$thm_black] #[fg=$thm_black,bg=$thm_magenta]  %a %b %d %Y, %H:%M "

setw -g window-status-format " #[fg=$thm_black,bg=$thm_blue]  #I:#[fg=$thm_black,bg=$thm_blue]#W "
setw -g window-status-current-format " #[fg=$thm_black,bg=$thm_orange]  #I:#[fg=$thm_black,bg=$thm_orange]#W "

setw -g clock-mode-colour "${thm_blue}"
setw -g mode-style "fg=${thm_orange} bg=${thm_bg} bold"

run -b '~/.tmux/plugins/tpm/tpm'
#  
