# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum' 
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-copycat'

# remap prefix from 'C-b' to 'C-a' unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind C-p previous-window
bind C-n next-window

# Enable mouse mode (tmux 2.1 and above) 
set -g mouse on
set -g base-index 1
set -g allow-rename off
setw -g pane-base-index 1
set -g @yank_with_mouse on
set -s default-terminal 'screen-256color'

# Undercurl
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Continuum
set -g @continuum-restore 'on'

setw -g history-limit 50000000

# --> Catppuccin
thm_bg="#1e1e2e"
thm_fg="#c6d0f5"
thm_cyan="#74c7ec"
thm_black="#15121c"
thm_gray="#313244"
thm_magenta="#cba6f7"
thm_pink="#f5c2e7"
thm_red="#f38ba8"
thm_green="#a6e3a1"
thm_yellow="#f9e2af"
thm_blue="#87b0f9"
thm_orange="#fab387"
thm_black4="#181825"

# VSCode
# thm_bg="#1e1e1e"
# thm_fg="#d4d4d4"
# thm_cyan="#74c7ec"
# thm_black="#15121c"
# thm_gray="#313244"
# thm_magenta="#cba6f7"
# thm_pink="#f5c2e7"
# thm_red="#f38ba8"
# thm_green="#a6e3a1"
# thm_yellow="#f9e2af"
# thm_blue="#87b0f9"
# thm_orange="#fab387"
# thm_black4="#181825"

# ----------------------------=== Theme ===--------------------------

# status
set -g status-position bottom
set -g status "on"
set -g status-bg "${thm_bg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# messages
set -g message-style fg="${thm_blue}",bg="${thm_bg}",align="centre"
set -g message-command-style fg="${thm_blue}",bg="${thm_bg}",align="centre"

# panes
set -g pane-border-style fg="${thm_gray}"
set -g pane-active-border-style fg="${thm_blue}"

# windows
setw -g window-status-activity-style fg="${thm_fg}",bg="${thm_bg}",none
setw -g window-status-separator ""
setw -g window-status-style fg="${thm_fg}",bg="${thm_bg}",none

# --------=== Statusline

set -g status-left "#{?client_prefix,#[fg=$thm_red],#[fg=$thm_green]}#{?client_prefix,#[bg=$thm_red],#[bg=$thm_green]}#[fg=$thm_bg] #{?client_prefix,#[bg=$thm_red],#[bg=$thm_green]}#[fg=$thm_bg] #S #{?client_prefix,#[fg=$thm_red],#[fg=$thm_green]}#[bg=$thm_bg]"
set -g status-right "#[fg=$thm_magenta,bg=$thm_bg]#[fg=$thm_bg,bg=$thm_magenta] %d %b %Y, %H:%M #[fg=$thm_magenta,bg=$thm_bg]"

# current_dir
setw -g window-status-format " #[fg=$thm_blue,bg=$thm_bg]#[fg=$thm_bg,bg=$thm_blue] #I#[fg=$thm_bg,bg=$thm_blue] #W #[fg=$thm_blue,bg=$thm_bg]"
setw -g window-status-current-format " #[fg=$thm_orange,bg=$thm_bg]#[fg=$thm_bg,bg=$thm_orange] #I#[fg=$thm_bg,bg=$thm_orange] #W #[fg=$thm_orange,bg=$thm_bg]"

# parent_dir/current_dir
# setw -g window-status-format "#[fg=colour232,bg=colour111] #I #[fg=colour222,bg=colour235] #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) "
# setw -g window-status-current-format "#[fg=colour232,bg=colour208] #I #[fg=colour255,bg=colour237] #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) "

# --------=== Modes
setw -g clock-mode-colour "${thm_blue}"
setw -g mode-style "fg=${thm_orange} bg=${thm_bg} bold"
  
run -b '~/.tmux/plugins/tpm/tpm'
