font_family      Hack Nerd Font Mono Regular
bold_font        Hack Nerd Font Mono Bold
italic_font      Hack Nerd Font Mono Italic
bold_italic_font Hack Nerd Font Mono Bold Italic
font_size 13.5
scrollback_lines 10000
window_padding_width 3
cursor_blink_interval 0
window_margin_width 0
background_opacity 0.95
tab_bar_margin_width 5.0
tab_bar_style powerline
tab_powerline_style angled
tab_title_template "{index}: {title}"

tab_bar_edge bottom
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up

map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab
map ctrl+shift+, set_tab_title

map ctrl+shift+n next_layout


# One Dark by Giuseppe Cesarano, https://github.com/GiuseppeCesarano
# This work is licensed under the terms of the GPL-2.0 license.
# For a copy, see https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html.

foreground #dcdfe4
background #282c34
cursor #cccccc
color0 #282c34
color1 #e06c75
color2 #98c379
color3 #e5c07b
color4 #61afef
color5 #c678dd
color6 #56b6c2
color7 #dcdfe4
color8 #555753
color9 #d19a66
color10 #56b6c2
color11 #e5c07b
color12 #61afef
color13 #be5046
color14 #56b6c2
color15 #abb2bf
selection_foreground #282c34
selection_background #979eab

# startup_session ~/.config/kitty/session.conf
startup_session none
