font_family      JetBrains Mono Medium Nerd Font Complete
bold_font        JetBrains Mono Bold Nerd Font Complete
italic_font      JetBrains Mono Medium Italic Nerd Font Complete
bold_italic_font JetBrains Mono Bold Italic Nerd Font Complete

font_size 13
scrollback_lines 10000
window_padding_width 5
window_margin_width 0
background_opacity 0.97
tab_bar_margin_width 5.0
tab_bar_style powerline
tab_powerline_style angled
tab_title_template "{index}: {title}"
cursor_shape block
cursor_blink_interval 0
disable_ligatures always
remember_window_size no
initial_window_width 120c
initial_window_height 30c
adjust_line_height 100%
shell_integration disabled
tab_bar_edge bottom
confirm_os_window_close 0

symbol_map U+f101-U+f208 nonicons
vim:ft=kitty

# name:     Catppuccin-Mocha
# author:   Pocco81 (https://github.com/Pocco81)
# license:  MIT
# upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
# blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5E0DC

# Cursor colors
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# URL underline color when hovering with mouse
url_color               #F5E0DC

# Kitty window border colors
active_border_color     #B4BEFE
inactive_border_color   #6C7086
bell_border_color       #F9E2AF

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111B
active_tab_background   #CBA6F7
inactive_tab_foreground #CDD6F4
inactive_tab_background #181825
tab_bar_background      #11111B

# Colors for marks (marked text in the terminal)
mark1_foreground #1E1E2E
mark1_background #B4BEFE
mark2_foreground #1E1E2E
mark2_background #CBA6F7
mark3_foreground #1E1E2E
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

# magenta
color5  #F5C2E7
color13 #F5C2E7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8

# # symbol_map U+f101-U+f208 nonicons

# vscode dark color scheme for Kitty
# By https://github/mofiqul

# foreground            #d4d4d4
# background            #1e1e1e
# selection_foreground  #1e1e1e
# selection_background  #d7ba7d
# url_color             #0087BD

# # black
# color0   #1e1e1e
# color8   #808080

# # red
# color1   #f44747
# color9   #f44747

# # green
# color2   #608b4e
# color10  #608b4e

# # yellow
# color3   #dcdcaa
# color11  #dcdcaa

# # blue
# color4  #569cd6
# color12 #569cd6

# # magenta
# color5   #c678dd
# color13  #c678dd

# # cyan
# color6   #56b6c2
# color14  #56b6c2

# # white
# color7   #d4d4d4
# color15  #d4d4d4

# vim:ft=kitty

## name: Tokyo Night Storm
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty_tokyonight_storm.conf


# background #24283b
# foreground #c0caf5
# selection_background #364A82
# selection_foreground #c0caf5
# url_color #73daca
# cursor #c0caf5

# # Tabs
# active_tab_background #7aa2f7
# active_tab_foreground #1f2335
# inactive_tab_background #292e42
# inactive_tab_foreground #545c7e
# #tab_bar_background #1D202F

# # normal
# color0 #1D202F
# color1 #f7768e
# color2 #9ece6a
# color3 #e0af68
# color4 #7aa2f7
# color5 #bb9af7
# color6 #7dcfff
# color7 #a9b1d6

# # bright
# color8 #414868
# color9 #f7768e
# color10 #9ece6a
# color11 #e0af68
# color12 #7aa2f7
# color13 #bb9af7
# color14 #7dcfff
# color15 #c0caf5

# # extended colors
# color16 #ff9e64
# color17 #db4b4b
