require("mappings.custom")
require("mappings.telescope")
require("mappings.neotree")
require("mappings.harpoon")
-- require("mappings.neoformat")
require("mappings.buffer_manager")
require("mappings.bufdelete")
require("mappings.trouble")
require("mappings.gitsigns")
require("mappings.spectre")
require("mappings.git")
require("mappings.formatter")
