require("mappings.custom")
require("mappings.telescope")
require("mappings.neotree")
require("mappings.harpoon")
require("mappings.buffer_manager")
require("mappings.bufdelete")
require("mappings.trouble")
require("mappings.gitsigns")
require("mappings.neotest")
require("mappings.diffview")
require("mappings.conform")
-- require("mappings.neoformat")
-- require("mappings.formatter")
-- require("mappings.spectre")
-- require("mappings.git")
