require("mappings.custom")
require("mappings.telescope")
require("mappings.neotree")
require("mappings.harpoon")
require("mappings.neoformat")
require("mappings.cybu")
require("mappings.bufdelete")
require("mappings.trouble")
require("mappings.gitsigns")
require("mappings.jabs")
require("mappings.spectre")
-- require("mappings.nvimtree")
-- require("mappings.bufferline")
