require("leiswatch.keymap.bufdelete")
require("leiswatch.keymap.buffer_manager")
-- require("leiswatch.keymap.conform")
require("leiswatch.keymap.custom")
require("leiswatch.keymap.diffview")
require("leiswatch.keymap.gitsigns")
require("leiswatch.keymap.harpoon")
require("leiswatch.keymap.neotree")
require("leiswatch.keymap.oil")
require("leiswatch.keymap.telescope")
require("leiswatch.keymap.trouble")
-- require("leiswatch.keymap.git")
