return {
	"stevearc/conform.nvim",
	enabled = true,
	event = { "BufRead" },
	opts = {
		formatters_by_ft = {
			lua = { "stylua" },
			rust = { "rustfmt" },
			go = { "goimports", "gofmt" },
			templ = { "templ" },
			c = { "clang-format" },
			cpp = { "clang-format" },
			python = { "black", "yapf" },
			astro = { "prettierd" },
			svelte = { "prettierd" },
			vue = { "prettierd" },
			html = { "prettierd" },
			javascript = { "prettierd" },
			typescript = { "prettierd" },
			javacriptreact = { "prettierd" },
			typescriptreact = { "prettierd" },
			css = { "prettierd" },
			scss = { "prettierd" },
			sass = { "prettierd" },
			less = { "prettierd" },
			yaml = { "prettierd" },
			json = { "prettierd" },
			jsonc = { "prettierd" },
			bash = { "shfmt" },
			zsh = { "shfmt" },
			zig = { "zigfmt" },
			["*"] = { "trim_newlines", "trim_whitespace" },
		},
	},
}
