return {
	"stevearc/conform.nvim",
    enabled = true,
	opts = {
		formatters_by_ft = {
			lua = { "stylua" },
			rust = { "rustfmt" },
			go = { "goimports", "gofumpt" },
			templ = { "templ" },
			c = { "clang-format" },
			cpp = { "clang-format" },
			python = { "black", "yapf" },
			astro = { "prettier" },
			svelte = { "prettier" },
			vue = { "prettier" },
			html = { "prettier" },
			javascript = { "prettier" },
			typescript = { "prettier" },
			javacriptreact = { "prettier" },
			typescriptreact = { "prettier" },
			css = { "prettier" },
			scss = { "prettier" },
			sass = { "prettier" },
			less = { "prettier" },
			yaml = { "prettier" },
			json = { "prettier" },
			jsonc = { "prettier" },
			bash = { "shfmt" },
			zsh = { "shfmt" },
			zig = { "zigfmt" },
			["*"] = { "trim_newlines", "trim_whitespace" },
		},
	},
}
