return {
	"stevearc/conform.nvim",
	enabled = true,
	event = { "BufRead" },
	opts = {
		notify_on_error = false,
		formatters_by_ft = {
			lua = { "stylua" },
			rust = { "rustfmt" },
			go = { "goimports", "gofmt" },
			templ = { "templ" },
			c = { "clang-format" },
			cpp = { "clang-format" },
			python = { "black", "yapf" },
			astro = { "prettier", "prettierd", stop_after_first = true },
			svelte = { "prettier", "prettierd", stop_after_first = true },
			vue = { "prettier", "prettierd", stop_after_first = true },
			html = { "prettier", "prettierd", stop_after_first = true },
			javascript = { "prettier", "prettierd", stop_after_first = true },
			typescript = { "prettier", "prettierd", stop_after_first = true },
			javacriptreact = { "prettier", "prettierd", stop_after_first = true },
			typescriptreact = { "prettier", "prettierd", stop_after_first = true },
			css = { "prettier", "prettierd", stop_after_first = true },
			scss = { "prettier", "prettierd", stop_after_first = true },
			sass = { "prettier", "prettierd", stop_after_first = true },
			less = { "prettier", "prettierd", stop_after_first = true },
			yaml = { "prettier", "prettierd", stop_after_first = true },
			json = { "prettier", "prettierd", stop_after_first = true },
			jsonc = { "prettier", "prettierd", stop_after_first = true },
			bash = { "shfmt" },
			zsh = { "shfmt" },
			zig = { "zigfmt" },
			["*"] = { "trim_newlines", "trim_whitespace" },
		},
	},
}
