require("catppuccin").setup({
	flavour = "mocha",
	transparent_background = true,
	term_colors = true,
	no_italic = true,
	styles = {
		comments = { "italic" },
		conditionals = {},
		loops = {},
		functions = {},
		keywords = {},
		strings = {},
		variables = {},
		numbers = {},
		booleans = {},
		properties = {},
		types = {},
		operators = {},
	},
	custom_highlights = function()
		return {
			FloatBorder = { fg = "#89b4fa", bg = "NONE" },
			TelescopeBorder = { fg = "#89b4fa", bg = "NONE" },
			TelescopePreviewBorder = { fg = "#89b4fa", bg = "NONE" },
			TelescopeResultsBorder = { fg = "#89b4fa", bg = "NONE" },
			TelescopePromptBorder = { fg = "#89b4fa", bg = "NONE" },
			TelescopePromptTitle = { fg = "#cdd6f4", bg = "NONE" },
			TelescopePreviewTitle = { fg = "#cdd6f4", bg = "NONE" },
			WhichKeyBorder = { fg = "#89b4fa", bg = "NONE" },
			CodeActionNormal = { fg = "#cdd6f4", bg = "NONE" },
			CodeActionBorder = { fg = "#89b4fa", bg = "NONE" },
			CodeActionText = { fg = "#cdd6f4", bg = "NONE" },
			CodeActionNumber = { fg = "#a6e3a1", bg = "NONE" },
			ActionPreviewNormal = { fg = "#cdd6f4", bg = "NONE" },
			ActionPreviewBorder = { fg = "#89b4fa", bg = "NONE" },
			ActionPreviewTitle = { fg = "#cdd6f4", bg = "NONE" },
			FloatTitle = { fg = "#cdd6f4", bg = "NONE" },
			CybuFocus = { bg = "#313244" },
		}
	end,
	integrations = {
		aerial = false,
		barbar = true,
		beacon = true,
		cmp = true,
		coc_nvim = false,
		dashboard = true,
		fern = false,
		fidget = true,
		gitgutter = true,
		gitsigns = true,
		harpoon = true,
		hop = false,
		illuminate = false,
		leap = false,
		lightspeed = false,
		lsp_saga = false,
		lsp_trouble = true,
		markdown = true,
		mason = true,
		mini = false,
		neogit = true,
		neotest = false,
		neotree = true,
		noice = false,
		notify = false,
		nvimtree = true,
		overseer = false,
		pounce = false,
		semantic_tokens = false,
		symbols_outline = false,
		telekasten = false,
		telescope = true,
		treesitter = true,
		treesitter_context = true,
		ts_rainbow = false,
		vim_sneak = false,
		vimwiki = false,
		which_key = true,
		-- Special integrations, see https://github.com/catppuccin/nvim#special-integrations
		dap = {
			enabled = false,
			enable_ui = false,
		},
		indent_blankline = {
			enabled = true,
			colored_indent_levels = false,
		},
		native_lsp = {
			enabled = true,
			virtual_text = {
				errors = { "italic" },
				hints = { "italic" },
				warnings = { "italic" },
				information = { "italic" },
			},
			underlines = {
				errors = { "underline" },
				hints = { "underline" },
				warnings = { "underline" },
				information = { "underline" },
			},
		},
		navic = {
			custom_bg = "NONE",
			enabled = true,
		},
	},
})

vim.cmd.colorscheme("catppuccin")
