require("catppuccin").setup({
	flavour = "mocha",
	transparent_background = true,
	term_colors = true,
	show_end_of_buffer = false,
	no_italic = true,
	-- styles = {
	-- 	comments = {},
	-- 	conditionals = {},
	-- 	loops = {},
	-- 	functions = {},
	-- 	keywords = {},
	-- 	strings = {},
	-- 	variables = {},
	-- 	numbers = {},
	-- 	booleans = {},
	-- 	properties = {},
	-- 	types = {},
	-- 	operators = {},
	-- },
	custom_highlights = function(color)
		return {
			FloatBorder = { fg = color.surface1, bg = "NONE" },
			FloatTitle = { fg = color.text, bg = "NONE" },
			HarpoonBorder = { fg = color.surface1, bg = "NONE" },
			NeotreeNormal = { fg = color.text, bg = "NONE" },
			Neotree = { fg = color.text, bg = "NONE" },
			TelescopeBorder = { fg = color.surface1, bg = "NONE" },
			TelescopePreviewBorder = { fg = color.surface1, bg = "NONE" },
			TelescopeResultsBorder = { fg = color.surface1, bg = "NONE" },
			TelescopePromptBorder = { fg = color.surface1, bg = "NONE" },
			TelescopePromptTitle = { fg = color.text, bg = "NONE" },
			TelescopePreviewTitle = { fg = color.text, bg = "NONE" },
			TelescopeResultsTitle = { fg = color.text, bg = "NONE" },
			TelescopePromptPrefix = { fg = color.text, bg = "NONE" },
			TelescopeSelection = { fg = color.text, bg = color.surface1 },
			TelescopeSelectionCaret = { fg = color.text, bg = color.surface1 },
			CodeActionNormal = { fg = color.text, bg = "NONE" },
			CodeActionBorder = { fg = color.surface1, bg = "NONE" },
			CodeActionText = { fg = color.text, bg = "NONE" },
			CodeActionNumber = { fg = color.green, bg = "NONE" },
			ActionPreviewNormal = { fg = color.text, bg = "NONE" },
			ActionPreviewBorder = { fg = color.surface1, bg = "NONE" },
			ActionPreviewTitle = { fg = color.text, bg = "NONE" },
			CursorLineNr = { fg = color.text, bg = "NONE" },
			LineNr = { fg = color.text, bg = "NONE" },
			LineNrAbove = { fg = color.surface1, bg = "NONE" },
			LineNrBelow = { fg = color.surface1, bg = "NONE" },
			ColorColumn = { fg = "NONE", bg = color.surface0 },
			TreesitterContext = { fg = "NONE", bg = color.mantle },
			TreesitterContextBottom = { bg = color.mantle },
			TreesitterContextLineNumberBottom = { bg = color.mantle },
			TreesitterContextLineNumber = { fg = color.text, bg = color.mantle },
			MatchParen = { bg = color.blue, fg = color.base },
			MatchWord = { bg = color.blue, fg = color.base },
			NeoTreeIndentMarker = { bg = "NONE", fg = color.surface0 },
			Directory = { bg = color.mantle, fg = color.text },
            IncSearch = {fg = color.base, bg = color.blue},
		}
	end,
	integrations = {
		aerial = false,
        alpha = true,
		barbar = false,
		beacon = false,
		cmp = true,
		coc_nvim = false,
		dashboard = false,
		fern = false,
		fidget = true,
		gitsigns = true,
		harpoon = true,
		hop = false,
		illuminate = false,
		leap = false,
		lightspeed = false,
		lsp_saga = false,
		lsp_trouble = false,
		markdown = true,
		mason = true,
		mini = false,
		neogit = false,
		neotest = false,
		neotree = true,
		noice = false,
		notify = false,
		nvimtree = false,
		overseer = false,
		pounce = false,
		semantic_tokens = true,
		symbols_outline = false,
		telekasten = false,
		telescope = {
			enabled = true,
			-- style = "nvchad"
		},
		treesitter = true,
		treesitter_context = true,
		ts_rainbow = false,
		ts_rainbow2 = false,
		rainbow_delimiters = false,
		vim_sneak = false,
		vimwiki = true,
		which_key = false,
		window_picker = false,
		dap = false,
		indent_blankline = {
			enabled = false,
			scope_color = "lavender",
			colored_indent_levels = false,
		},
		native_lsp = {
			enabled = true,
			virtual_text = {
				errors = { "italic" },
				hints = { "italic" },
				warnings = { "italic" },
				information = { "italic" },
			},
			underlines = {
				errors = { "underline" },
				hints = { "underline" },
				warnings = { "underline" },
				information = { "underline" },
			},
		},
	},
})

vim.cmd.colorscheme("catppuccin")
