require("configs.catppuccin")
require("configs.lspconfig")
require("configs.none_ls")
require("configs.cmp")
require("configs.treesitter")
require("configs.treesitter_context")
require("configs.autopairs")
require("configs.bqf")
require("configs.buffer_manager")
require("configs.colorizer")
require("configs.comment")
require("configs.commentstring")
require("configs.diffview")
require("configs.dressing")
require("configs.fidget")
require("configs.friendly_snippets")
require("configs.gitsigns")
require("configs.harpoon")
require("configs.lualine")
require("configs.neotree")
require("configs.surround")
require("configs.telescope")
require("configs.todo_comments")
require("configs.alpha")

-- require("configs.trouble")
-- require("configs.neotest")
-- require("configs.conform")
-- require("configs.lint")
-- require("configs.noice")
