require("configs.catppuccin")
require("configs.alpha")
require("configs.auto_hlsearch")
require("configs.bqf")
require("configs.buffer_manager")
require("configs.cmp")
require("configs.colorizer")
require("configs.comment")
require("configs.dressing")
require("configs.fidget")
require("configs.friendly_snippets")
require("configs.gitsigns")
require("configs.harpoon")
require("configs.icons")
require("configs.lsp")
require("configs.lspsaga")
require("configs.lualine")
require("configs.neotree")
require("configs.noice")
require("configs.null_ls")
require("configs.surround")
require("configs.telescope")
require("configs.todo_comments")
require("configs.treesitter")
require("configs.treesitter_context")
require("configs.trouble")
-- require("configs.barbecue")
-- require("configs.git_conflict")
-- require("configs.window_picker")
-- require("configs.flash")
-- require("configs.which_key")
-- require("configs.nui")
-- require("configs.autopairs")
