require("configs.alpha")
require("configs.auto_hlsearch")
require("configs.autopairs")
require("configs.bqf")
require("configs.buffer_manager")
-- require("configs.bufferline")
require("configs.catppuccin")
require("configs.cmp")
require("configs.codeium")
require("configs.colorizer")
require("configs.comment")
require("configs.commentstring")
require("configs.diffview")
require("configs.dressing")
require("configs.fidget")
require("configs.friendly_snippets")
require("configs.gitsigns")
require("configs.harpoon")
require("configs.icons")
require("configs.neodev")
require("configs.lsp")
require("configs.lualine")
require("configs.neotest")
require("configs.neotree")
require("configs.noice")
require("configs.none_ls")
require("configs.surround")
require("configs.telescope")
require("configs.todo_comments")
require("configs.treesitter")
require("configs.treesitter_context")
require("configs.trouble")
require("configs.ibl")
require("configs.barbecue")
-- require("configs.lint")
-- require("configs.conform")
-- require("configs.window")
-- require("configs.barbecue")
-- require("configs.timeout")
-- require("configs.tokyonight")
-- require("configs.hardtime")
-- require("configs.formatter")
