require("lint").linters_by_ft = {
	go = { "golangcilint" },
	python = { "pylint" },
	json = { "jsonlint" },
	yaml = { "yamllint" },
	scss = { "stylelint" },
	sass = { "stylelint" },
	css = { "stylelint" },
	less = { "stylelint" },
	-- lua = { "luacheck" },
	-- astro = { "eslint_d" },
	-- javascript = { "eslint_d" },
	-- javascriptreact = { "eslint_d" },
	-- typescript = { "eslint_d" },
	-- typescriptreact = { "eslint_d" },
}
