local helpers = require("leiswatch.helpers")

vim.keymap.set("n", "P", "]P", helpers.keymap_opts)
vim.keymap.set("n", "p", "]p", helpers.keymap_opts)
vim.keymap.set("n", "<leader>vv", "<C-^>", helpers.keymap_opts)
vim.keymap.set("n", "<leader>ss", ":split<Return><C-w>w", helpers.keymap_opts)
vim.keymap.set("n", "<leader>sv", ":vsplit<Return><C-w>w", helpers.keymap_opts)
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", helpers.keymap_opts)
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", helpers.keymap_opts)
vim.keymap.set("n", "<C-d>", "<C-d>zz", helpers.keymap_opts)
vim.keymap.set("n", "<C-u>", "<C-u>zz", helpers.keymap_opts)
-- vim.keymap.set("i", "<C-c>", "<Esc>", helpers.keymap_opts)
vim.keymap.set("x", "<leader>p", '"_dP', helpers.keymap_opts)
vim.keymap.set({ "n", "v" }, "<leader>y", '"+y', helpers.keymap_opts)
vim.keymap.set("n", "<leader>Y", '"+Y', helpers.keymap_opts)
vim.keymap.set("n", "n", "nzzzv", helpers.keymap_opts)
vim.keymap.set("n", "N", "Nzzzv", helpers.keymap_opts)
vim.keymap.set({ "i", "n" }, "<esc>", "<cmd>noh<cr><esc>", helpers.keymap_opts)
vim.keymap.set("v", "<", "<gv", helpers.keymap_opts)
vim.keymap.set("v", ">", ">gv", helpers.keymap_opts)
vim.keymap.set("n", "q:", "", helpers.keymap_opts)
vim.keymap.set("n", "q?", "", helpers.keymap_opts)
vim.keymap.set("n", "<leader>cn", vim.cmd.cnext, helpers.keymap_opts)
vim.keymap.set("n", "<leader>cp", vim.cmd.cprevious, helpers.keymap_opts)
vim.keymap.set("n", "=ap", "mz=ap'z:delmarks z<cr>", helpers.keymap_opts)
