local helpers = require("leiswatch.helpers")
local builtin = require("telescope.builtin")

vim.keymap.set("n", "<C-p>", builtin.find_files, helpers.keymap_opts)
vim.keymap.set("n", "<leader>ff", builtin.find_files, helpers.keymap_opts)
vim.keymap.set("n", "<leader>fl", builtin.live_grep, helpers.keymap_opts)
vim.keymap.set({ "n", "v" }, "<leader>fw", builtin.grep_string, helpers.keymap_opts)
vim.keymap.set("n", "<leader>fb", builtin.buffers, helpers.keymap_opts)
vim.keymap.set("n", "<leader>fh", builtin.help_tags, helpers.keymap_opts)
vim.keymap.set("n", "<leader>fj", ":Telescope harpoon marks<CR>", helpers.keymap_opts)
