gui:
  showIcons: true
  theme:
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#313244"
    inactiveBorderColor:
      - "#313244"
    activeBorderColor:
      - "#89b4fa"
      - bold
    optionsTextColor:
      - white
