gui:
  nerdFontsVersion: "3"
  # border: rounded
  showIcons: false
  theme:
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#313244"
    inactiveBorderColor:
      - "#6c7086"
    activeBorderColor:
      - "#89b4fa"
      - bold
    optionsTextColor:
      - white
