# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind C-p previous-window
bind C-n next-window

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

set -g default-terminal "screen-256color"  # Setting the correct term
source-file ~/.tmux/themes/tomorrow-night-eighties.tmux

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-pain-control'

run '~/.tmux/plugins/tpm/tpm'

