font_family SauceCodePro Nerd Font Mono Medium
bold_font        SauceCodePro Nerd Font Mono Bold
italic_font      SauceCodePro Nerd Font Mono Italic
bold_italic_font SauceCodePro Nerd Font Mono Bold Italic
font_size 14.0
scrollback_lines 10000
window_padding_width 0 3
cursor_blink_interval 0
window_margin_width 0
background_opacity 0.98
title Kitty
# Base16 Tomorrow Night - kitty color config
# Scheme by Chris Kempson (http://chriskempson.com)
background #2d2d2d
foreground #cccccc
selection_background #cccccc
selection_foreground #2d2d2d
url_color #b4b7b4
cursor #cccccc
active_border_color #999999
inactive_border_color #393939
active_tab_background #2d2d2d
active_tab_foreground #cccccc
inactive_tab_background #393939
inactive_tab_foreground #b4b7b4
tab_bar_background #393939

# normal
color0 #2d2d2d
color1 #f2777a
color2 #99cc99
color3 #ffcc66
color4 #6699cc
color5 #cc99cc
color6 #66cccc
color7 #cccccc

# bright
color8 #999999
color9 #f2777a
color10 #99cc99
color11 #ffcc66
color12 #6699cc
color13 #cc99cc
color14 #66cccc
color15 #ffffff

# extended base16 colors
color16 #f99157
color17 #a3685a
color18 #393939
color19 #515151
color20 #b4b7b4
color21 #e0e0e0

# Base16 OneDark - kitty color config
# Scheme by Lalit Magant (http://github.com/tilal6991)
# background #282c34
# foreground #abb2bf
# selection_background #abb2bf
# selection_foreground #282c34
# url_color #565c64
# cursor #abb2bf
# active_border_color #545862
# inactive_border_color #353b45
# active_tab_background #282c34
# active_tab_foreground #abb2bf
# inactive_tab_background #353b45
# inactive_tab_foreground #565c64
# tab_bar_background #353b45

# # normal
# color0 #282c34
# color1 #e06c75
# color2 #98c379
# color3 #e5c07b
# color4 #61afef
# color5 #c678dd
# color6 #56b6c2
# color7 #abb2bf

# # bright
# color8 #545862
# color9 #e06c75
# color10 #98c379
# color11 #e5c07b
# color12 #61afef
# color13 #c678dd
# color14 #56b6c2
# color15 #c8ccd4

# # extended base16 colors
# color16 #d19a66
# color17 #be5046
# color18 #353b45
# color19 #3e4451
# color20 #565c64
# color21 #b6bdca
