new_tab editor
launch zsh
cd ~/Projects/

new_tab dev
layout grid
launch zsh
cd ~/Projects
launch zsh
cd ~/Projects
launch zsh
cd ~/Projects
launch zsh
cd ~/Projects

new_tab desktop
layout tall
launch zsh
cd ~
focus
launch zsh
cd ~

new_tab bpytop
launch bpytop
