#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart
/home/leiswatch/.config/bspwm/scripts/autostart.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#89b4fa"
bspc config active_border_color "#89b4fa"
bspc config normal_border_color "#313244"
bspc config top_padding 40

bspc rule -a Pavucontrol state=floating
bspc rule -a Gnome-calculator state=floating

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
