;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #1E1E2E
background-alt = #313244
foreground = #cdd6f4
foreground-alt = #bac2de
primary = #89b4fa

white = #cdd6f4
black = #11111b
red = #f38ba8
pink = #f5c2e7
purple = #cba6f7
blue = #89b4fa
cyan = #74c7ec
teal = #94e2d5
green = #a6e3a1
lime = #89dceb
yellow = #f9e2af
amber = #fab387
orange = #fab387
brown = #f2cdcd
gray = #6c7086
indigo = #74c7ec
blue-gray = #f5e0dc

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
