local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{ "catppuccin/nvim", name = "catppuccin" },
	{ "neovim/nvim-lspconfig" },
	{
		"nvim-treesitter/nvim-treesitter",
		build = function()
			local ts_update = require("nvim-treesitter.install").update({ with_sync = true })
			ts_update()
		end,
	},
	{ "HiPhish/nvim-ts-rainbow2" },
	{ "windwp/nvim-ts-autotag" },
	{ "JoosepAlviste/nvim-ts-context-commentstring" },
	{ "nvim-treesitter/nvim-treesitter-context" },
	{ "williamboman/mason.nvim" },
	{ "williamboman/mason-lspconfig.nvim" },
	{ "WhoIsSethDaniel/mason-tool-installer.nvim" },
	{ "hrsh7th/cmp-nvim-lsp" },
	{ "hrsh7th/cmp-buffer" },
	{ "hrsh7th/cmp-path" },
	{ "hrsh7th/cmp-cmdline" },
	{ "hrsh7th/nvim-cmp" },
	{ "L3MON4D3/LuaSnip" },
	{ "saadparwaiz1/cmp_luasnip" },
	{ "hrsh7th/cmp-nvim-lua" },
	{ "rafamadriz/friendly-snippets" },
	{ "nvim-lualine/lualine.nvim", dependencies = { "kyazdani42/nvim-web-devicons", opt = true } },
	{ "windwp/nvim-autopairs" },
	{ "numToStr/Comment.nvim" },
	{ "stevearc/dressing.nvim" },
	{ "j-hui/fidget.nvim" },
	{ "onsails/lspkind.nvim" },
	{ "kyazdani42/nvim-web-devicons" },
	{ "nvim-lua/plenary.nvim" },
	{ "nvim-telescope/telescope.nvim", tag = "0.1.2" },
	{ "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
	{ "ThePrimeagen/harpoon" },
	{ "NvChad/nvim-colorizer.lua" },
	{ "lewis6991/gitsigns.nvim" },
	{ "goolord/alpha-nvim" },
	-- { "sbdchd/neoformat" },
	{ "mhartington/formatter.nvim" },
	{ "kylechui/nvim-surround", version = "*" },
	{ "folke/trouble.nvim" },
	{ "famiu/bufdelete.nvim" },
	{ "kevinhwang91/nvim-bqf" },
	{ "MunifTanjim/nui.nvim" },
	{ "folke/noice.nvim" },
	{ "nvim-neo-tree/neo-tree.nvim", branch = "v3.x" },
	{ "mbbill/undotree" },
	{ "asiryk/auto-hlsearch.nvim" },
	{ "j-morano/buffer_manager.nvim" },
	{ "folke/todo-comments.nvim" },
	{ "pontusk/cmp-sass-variables" },
	{ "sindrets/diffview.nvim" },
	{ "mfussenegger/nvim-lint" },
	{ "pmizio/typescript-tools.nvim" },
	{ "akinsho/bufferline.nvim", version = "*" },
	{ "NeogitOrg/neogit" },
	{ "nvimdev/lspsaga.nvim" },
	-- { "jose-elias-alvarez/typescript.nvim" },
	-- { "tpope/vim-fugitive" },
	-- { "jose-elias-alvarez/null-ls.nvim" },
	-- { "andymass/vim-matchup" },
	-- { "akinsho/git-conflict.nvim" },
	-- { "utilyre/barbecue.nvim", name = "barbecue", version = "*", dependencies = { "SmiteshP/nvim-navic" } },
	-- { "folke/which-key.nvim" },
	-- { "s1n7ax/nvim-window-picker", version = "v1.*" },
	-- { "rebelot/kanagawa.nvim" },
}, {
	ui = {
		size = { width = 0.8, height = 0.8 },
		wrap = true,
		border = "rounded",
	},
})
