default_session = "home"
display_full_path = true
session_sort_order = "Alphabetical"

[[search_dirs]]
path = "/home/leiswatch/Projects"
depth = 10

[picker_colors]
highlight_color = "#313244"
highlight_text_color = "#fab387"
border_color = "#cdd6f4"
