[module/menu]
type    = custom/text

content            = 
content-foreground = ${colors.cyan}
content-padding    = 2

click-left         = rofi -show drun
click-right        = rofi -show window

[module/i3]
type = internal/i3

pin-workspaces = true

ws-icon-default = 

format = <label-state> <label-mode>

; Available tokens:
;   %mode%
; Default: %mode%
label-mode = %mode%
label-mode-padding = 1
label-mode-background = #e60053

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-focused = %name%
label-focused-foreground = ${colors.bg}
label-focused-background = ${colors.peach}
label-focused-underline = ${colors.yellow}
label-focused-padding = 2

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-unfocused = %name%
label-unfocused-padding = 2

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-visible = %icon%
label-visible-underline = #555555
label-visible-padding = 2

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-urgent = %icon%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-padding = 2

; Separator in between workspaces
; label-separator = |
label-separator-padding = 0
label-separator-foreground = ${colors.fg-alt}
