require'leiswatch.plugins'
require'leiswatch.treesitter'
require'leiswatch.lspinstall'
require'leiswatch.github_dark'
-- require'leiswatch.lsputils'
require'leiswatch.lightbulb'
require'leiswatch.cmp'
require'leiswatch.lspsaga'
require'leiswatch.alpha'
require'leiswatch.tree'
require'leiswatch.neoscroll'
require'leiswatch.autotag'
require'leiswatch.autopairs'
require'leiswatch.null'
require'leiswatch.telescope'
