require("leiswatch.plugins")
require("leiswatch.lspinstaller")
require("leiswatch.treesitter")
require("leiswatch.nvimCmp")
require("leiswatch.friendlySnippets")
require("leiswatch.nvimLualine")
require("leiswatch.indent")
require("leiswatch.pairs")
require("leiswatch.autotag")
-- require("leiswatch.onedark")
-- require("leiswatch.catppuccin")
require("leiswatch.vscode")
require("leiswatch.colorizer")
require("leiswatch.gitsigns")
require("leiswatch.comment")
require("leiswatch.nullls")
require("leiswatch.bufferline")
require("leiswatch.nvimtree")
require("leiswatch.alpha")
require("leiswatch.telescope")
require("leiswatch.dressing")
require("leiswatch.mappings")
