require("leiswatch.mappings")
require("leiswatch.plugins")
require("leiswatch.mason")
require("leiswatch.lspconfig")
require("leiswatch.treesitter")
require("leiswatch.cmp")
require("leiswatch.friendlySnippets")
require("leiswatch.lualine")
require("leiswatch.indent")
require("leiswatch.autotag")
require("leiswatch.colorizer")
require("leiswatch.gitsigns")
require("leiswatch.comment")
require("leiswatch.nullls")
require("leiswatch.nvimtree")
require("leiswatch.alpha")
require("leiswatch.telescope")
require("leiswatch.dressing")
require("leiswatch.numbers")
require("leiswatch.trouble")
require("leiswatch.autocommands")
require("leiswatch.worktrees")
require("leiswatch.catppuccin")
require("leiswatch.tokyonight")
require("leiswatch.whichkey")
require("leiswatch.nvimNumb")
require("leiswatch.bufferline")
require("leiswatch.webdevicons")
require("leiswatch.harpoon")
require("leiswatch.fidget")
require("leiswatch.autopairs")
--[[ require("leiswatch.notify") ]]
--[[ require("leiswatch.neogit") ]]
--[[ require("leiswatch.lspcolors") ]]
--[[ require("leiswatch.highlight") ]]
