return require("packer").startup(function()
	use("wbthomason/packer.nvim")
	use("olimorris/onedarkpro.nvim")
	use("neovim/nvim-lspconfig")
	use("williamboman/nvim-lsp-installer")
	use("hrsh7th/cmp-nvim-lsp")
	use("hrsh7th/cmp-buffer")
	use("hrsh7th/cmp-path")
	use("hrsh7th/cmp-cmdline")
	use("hrsh7th/nvim-cmp")
	use("L3MON4D3/LuaSnip")
	use("saadparwaiz1/cmp_luasnip")
	use("rafamadriz/friendly-snippets")
	use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
	use({ "nvim-telescope/telescope.nvim", requires = { { "nvim-lua/plenary.nvim" } } })
	use("nvim-telescope/telescope-ui-select.nvim")
	use("kyazdani42/nvim-web-devicons")
	use("onsails/lspkind.nvim")
	use("nvim-lualine/lualine.nvim")
	use("lukas-reineke/indent-blankline.nvim")
	use("windwp/nvim-autopairs")
	use("windwp/nvim-ts-autotag")
	use({ "catppuccin/nvim", as = "catppuccin" })
	use("Mofiqul/vscode.nvim")
	use("norcalli/nvim-colorizer.lua")
	use("f-person/git-blame.nvim")
	use("lewis6991/gitsigns.nvim")
	use("numToStr/Comment.nvim")
	use("JoosepAlviste/nvim-ts-context-commentstring")
	use("jose-elias-alvarez/nvim-lsp-ts-utils")
	use("jose-elias-alvarez/null-ls.nvim")
	use("kdheepak/lazygit.nvim")
	use({ "akinsho/bufferline.nvim", tag = "*", requires = "kyazdani42/nvim-web-devicons" })
	use("kyazdani42/nvim-tree.lua")
	use("famiu/bufdelete.nvim")
	use("goolord/alpha-nvim")
	use("p00f/nvim-ts-rainbow")
	use("sheerun/vim-polyglot")
	use("ray-x/go.nvim")
end)
